title       = "jsonplaceholder"
baseURL     = "https://jsonplaceholder-cli.tamnd.com/"
description = "CLI for JSONPlaceholder fake REST API"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/jsonplaceholder-cli"
